### PR TITLE
Remove incorrect "have" from 4.0.1 release blog

### PR DESCRIPTION
**Pull request by JohnVeness**

### CODE REVIEW

**Comment by YuriSizov** [comment]
This feels pretty arbitrary to me. Fixing typos in published articles is fine, but rewriting the language of them is not necessary.

**Comment by JohnVeness** [comment]
Understood. It was the incorrect "have" in the first sentence "Just three weeks ago we have published Godot 4.0" that really drew my attention. The other changes I just suggested in a "while I have the editor open" mood - they're not important.

**Comment by YuriSizov** [comment]
If this sentence is incorrect, feel free to update your PR to address only that :)

**Review by clayjohn — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Pull request merged**
