### PR TITLE
Add instant.page to speed up page loading

### PR DESCRIPTION
**Pull request by Calinou**
instant.page prefetches pages when the user hovers links for more than 65 milliseconds. This can be used to make navigation feel significantly faster.

Note that this will have no effect in Firefox when using uBlock Origin, as it forcibly disables prefetching.

See also https://github.com/godotengine/godot-docs/pull/3197.

### CODE REVIEW

**Comment by akien-mga** [comment]
I don't have a strong opinion on this, not sure if it's actually a good feature or not. WDYT @bojidar-bg?

**Comment by mhilbrunner** [comment]
We've added this to the docs, IMO while not groundbreaking it's a nice small improvement.

**Comment by bojidar-bg** [comment]
If we are fine with it in the docs, it should be okay in the main website.

**Comment by akien-mga** [comment]
Alright, let's merge once rebased then. @Calinou

**Comment by Calinou** [comment]
Rebased. I also updated instant.page to the latest available version in the process.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
