### PR TITLE
Showcase: Primal Light is releasing on Switch

### PR DESCRIPTION
**Pull request by akien-mga**
It will be released on 2022.11.24.

I was notified of it by porting/publisher [No Gravity Games](https://nogravitygames.com/) and there website indeed confirms the upcoming release.

### CODE REVIEW

**Review by Calinou — CHANGES_REQUESTED** [review]
The `primal-light.html` details page should also be updated to have the `switch` icon. I know it's not very DRY but it was the easiest way to implement the showcase :slightly_smiling_face:

**Comment by akien-mga** [comment]
Thanks for the review, it should be correct now I believe. Note that I didn't test the changes.

**Review by Calinou — APPROVED** [review]
Good to merge ~~**after** 2022-11-24 (don't merge before).~~

**Comment by akien-mga** [comment]
I think it's fine to merge even before, it shouldn't make much difference.

There's already a store page so users who notice this before Nov 24 could wishlist it: https://www.nintendo.com/store/products/primal-light-switch/

**Pull request merged**
