### PR TITLE
Updating news to display articles on a grid

### PR DESCRIPTION
**Pull request by coppolaemilio**
A small redesign of the news page to show the thumbnails without cropping them, have more articles per row.
Images are centered and 16/9 aspect ratio, so if they get cropped, the most important elements will be displayed.
It starts with a single column in mobile, and then it goes to two columns on 768px, and three after 1024px.
Avatars get pulled from the CMS and are called by using the provided `{{ post.user.getAvatarThumb() }}`

image

* The articles on the screenshot are placeholders I made locally

This is how it looks like in the ~~eye strain~~ light theme:

image

I considered adding tags and other information but ultimately decided to leave it as clean as possible. 

For reference, this is how it looks right now: 

image

There are still other areas of the News page I would like to update, so this is the first in a series of updates.

### CODE REVIEW

**Comment by Calinou** [comment]
Looks good, but the author/date text isn't very readable on the dark theme. Could you make it a bit brighter when using the dark theme? Once this is done, this should be good to merge :slightly_smiling_face:

**Comment by coppolaemilio** [comment]
> Looks good, but the author/date text isn't very readable on the dark theme. Could you make it a bit brighter when using the dark theme? Once this is done, this should be good to merge 🙂

Thanks! I tried using a color that was already a variable used on other text, but it is true that it doesn't have a lot of contrast with the background. I'll find another value and update it 👍

**Comment by coppolaemilio** [comment]
This is how the new placeholder avatar looks like and also more contrast on the info area:

image

@YuriSizov @Calinou should be ready to merge/publish whenever you are ready

**Review by YuriSizov — APPROVED** [review]
I've changed one small thing: avatars now load at 40 pixel, but display at 25 still. This reduces compression on this small image by a lot. Otherwise, I think this is good to go!

Note, that we would want to check the avatars upon going live, and maybe upload a placeholder for those that may be considered personal. We can keep the ones that match other public avatars of people (on GH, Twitter), or something abstract enough.

**Comment by YuriSizov** [comment]
Okay, I made it so Gravatar is never used, so our authors won't accidentally get assigned an image they'd rather not have. And we can fallback without it, so we're using an SVG now!

**Comment by YuriSizov** [comment]
Just one tiny fix that annoyed me about this page. Focused style for the tags is now correct:

image

It used to look like [this](https://user-images.githubusercontent.com/11782833/204104002-cbe1ff0b-e836-4701-b425-f38f9bcdcaef.png). We may want to make sure all focus styles look appropriate for their corresponding elements, but this was was really out there for some reason. And since this page will get more attention when we launch this, I decided to quickly fix it.

-----

The PR is as ready as it gets, I'm just taking the opportunity to tweak it even more before it gets merged. 🙃

**Comment by coppolaemilio** [comment]
This PR closes https://github.com/godotengine/godot-website/issues/64

**Comment by YuriSizov** [comment]
Thanks a bunch!

**Pull request merged**
