### PR TITLE
Features.html: Fixes up minor grammar issues

### PR DESCRIPTION
**Pull request by jacobpennington821**
Fix up minor grammar issues in features.html to do with godot 4.

### CODE REVIEW

**Comment by YuriSizov** [comment]
Thanks for fixing the typo, but why do we need an extra word there?

**Comment by jacobpennington821** [comment]
Just thought the sentence flowed better with it included, happy to remove not 😄

**Comment by YuriSizov** [comment]
I think it might be a bit too boastful, as our set is not yet comprehensive by some standards :)

**Comment by jacobpennington821** [comment]
All sorted, hopefully one day it will be comprehensive!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
