### PR TITLE
Optimize features page

### PR DESCRIPTION
**Pull request by MichaelJRM**
- Optimized the images carrousel
- Reordered requests to optimize FCP & LCP

**This pr depends on #806**

| Before  | After |
| ------------- | ------------- |
|  before | after
| before| after

### CODE REVIEW

**Comment by JohnVeness** [comment]
Out of interest, how do you obtain those performance measurement screenshots?

**Comment by MichaelJRM** [comment]
Chromium based browser -> F12 -> Lighthouse
Always with a private window and cache disabled so it doesn't interfere with the results


lighthouse

**Review by Calinou — APPROVED** [review]
Changes specific to the Features page work and look good to me.

**Comment by coppolaemilio** [comment]
I'm closing this PR as not planned. While the intentions are good, we are not going to be making significant changes to the current pages before we transition to the new site using hugo. Thanks!

**Pull request closed without merging**
