### PR TITLE
Add android logo to cross-platform asset

### PR DESCRIPTION
**Pull request by bits-by-brandon**
Replaces the Steamdeck logo with the Andoid logo on the homepage "Cross-platform" card. The steam-deck seems redundant given the steam logo already exists on this asset, and Android support seems like a big missing OS.

Also adds the missing nose

Screen Shot 2022-08-07 at 7 35 40 PM

### CODE REVIEW

**Comment by akien-mga** [comment]
I think we might have to use this logo instead of Android: https://source.android.com/setup/start/brands#robot-android

**Comment by bits-by-brandon** [comment]
Screen Shot 2022-08-08 at 9 30 11 PM

Updated logo

**Comment by bits-by-brandon** [comment]
@akien-mga Updated logo!

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
@bits-by-brandon We've had some additional thoughts, but they'll wait for another time. I'll merge and push it to production tomorrow.

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks

**Pull request merged**
