### PR TITLE
Grammar updates

### PR DESCRIPTION
**Pull request by jcs224**
Open source, when used as an adjective, becomes the compound word "open-source".

https://en.wikipedia.org/wiki/Open-source_software

### CODE REVIEW

**Comment by LikeLakers2** [comment]
You only need to make one PR -- your other two PRs (#67 and #68) contain changes present in this PR.

~~That being said, our doc writing guidelines ask for the use of the Oxford comma: http://docs.godotengine.org/en/latest/community/contributing/docs_writing_guidelines.html So I presume the website should do the same.~~

**Comment by jcs224** [comment]
Ah, sorry about the multiple PRs. I should have based them all off of the master branch, but I branched from each successive update. I'll clean it up.

I agree with using the Oxford comma, however it only applies when there are three or more items. This comma was used to separate two items. 

For example, if instead it said "you can help by fixing bugs, creating cool new features, or helping others", the commas would be appropriate. The same phrase without an Oxford comma would be "you can help by fixing bugs, creating cool new features or helping others". I agree this is more confusing, and am a fan of using the Oxford comma to quell the confusion. In this case, however, there are only two items, so no comma is necessary. "you can help by fixing bugs or creating cool new features".

**Comment by LikeLakers2** [comment]
Ah yeah, I misread what was being edited, so my bad. Ignore my comment about the Oxford comma. :)

**Comment by jcs224** [comment]
No worries. Should I just close the other two pull requests?

**Comment by LikeLakers2** [comment]
Woop, yeah. You seem to have already done so, though. 👍

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
