### PR TITLE
Anchor links to headings

### PR DESCRIPTION
**Pull request by Ymanawat**
- Made Anchor link icons appear when a heading hovers.
- Generates the id of headings on the page and links that id to headings.
- Generates a Link to that section by clicking the anchor icon.
- Don't make an anchor link to a heading that redirects to another web page, like a blog.
Issue : #214 

https://user-images.githubusercontent.com/81252768/218298143-7df8f50f-c707-457e-92ea-0a5e0c469f28.mp4

### CODE REVIEW

**Comment by YuriSizov** [comment]
I would prefer we looked into a build time solution to this.

**Comment by coppolaemilio** [comment]
I also think this was something more for text-heavy pages or blog posts, so I wouldn't add it to every page like it is shown here on the video.
Most of the time, this is needed to link to a specific part of an article (like the downloads section of a beta release).

**Comment by Ymanawat** [comment]
That makes sense to me. Though I thought about not doing it like that, but the docs also have these permalinks under every heading, so I kept it that way. 
I don't want to do it separately for each page, that's why I imported it to default, but I can do it on specific pages if needed. Is there anything i can do about this?

**Comment by Calinou** [comment]
> I don't want to do it separately for each page, that's why I imported it to default, but I can do it on specific pages if needed. Is there anything i can do about this?

You could apply the solution only if the current page's URL contains `/article/`.

**Comment by YuriSizov** [comment]
Since articles are generated as a Jekyll collection from MD files, there should be an opportunity to hook into the generator and add the necessary HTML to the page. (And then add the CSS for the icons to only appear on hover).

**Comment by Ymanawat** [comment]
> You could apply the solution only if the current page's URL contains `/article/`.


It could be done simply by importing the .js file in the article.html.
@YuriSizov Are you thinking of creating a plugin for adding anchor links to the heading in the template and letting them generate from the MD file? I think I can do it.

**Comment by YuriSizov** [comment]
Yes, it would be preferable to generate these links during build time. I'm not sure how pluggable is Jekyll, and it has disappointed me before, but I hope that this is doable.

**Comment by Ymanawat** [comment]
@YuriSizov @Calinou I managed to do it. I removed the `{{content}}` from the article layout and included my own HTML liquid template, which only modifies headings and adds anchors. I added CSS to the article layout itself. Is it going to work?

**Comment by YuriSizov** [comment]
I don't know, update your PR and we'll see :)

**Comment by YuriSizov** [comment]
So apparently (as noted in https://github.com/godotengine/godot-website/pull/574) Jekyll generates IDs for headings in articles. So we don't need a complex solution, I guess. Only a way to add an icon on hover to copy a permalink. This can be done in JS at this point.

Sorry for the runaround.

**Comment by Ymanawat** [comment]
>Jekyll generates IDs for headings in articles


Yes before I didn't know that so in the JS file I was generating the ids but then in Template, I'm not generating IDs but I'm changing `<h2 id="whats-new">What’s new</h2>` to `<h2 id="whats-new"> What’s new <a href="#whats-new" class="anchor-link" >🔗</a></h2>` so that the link got generated in this way and that link icon will point to this section. Should I revert back to that JS solution and remove the generation part and link directly?

**Comment by YuriSizov** [comment]
Yeah, let's go with a JS solution, sorry again.

**Comment by Ymanawat** [comment]
It's okay, Do we want to copy that link on click or keep it as in the above video so that the user will right-click and select copy link address from the more options?

**Comment by YuriSizov** [comment]
Copying on click would be more useful

**Comment by coppolaemilio** [comment]
Thank you for the PR @Ymanawat!

**Pull request merged**
