### PR TITLE
Make the main scrollbar follow user's color preference

### LINKED ISSUE #547: Scrollbars don't follow user's theme preference
image

Scrollbar is light themed when the rest of the website is dark themed.

Can be fixed by setting the [`color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme#adapting_to_color_schemes) property of `:root`:
```
:root {
  color-scheme: light dark;
}
```

### PR DESCRIPTION
**Pull request by Ymanawat**
Resolved the issue of the scrollbar having only light theme.

- *Bugsquad edit: This closes https://github.com/godotengine/godot-website/issues/547.*

### CODE REVIEW

**Comment by YuriSizov** [comment]
This is not the solution that we have discussed. We don't want to customize the look of the main scrollbar. All we need is for it to follow the user preference, which should be handled by the snippet in the OP of the issue.

**Review by YuriSizov — APPROVED** [review]
LGTM

**Comment by YuriSizov** [comment]
Thanks and congrats on the first merged pull request!

**Comment by Ymanawat** [comment]
Thanks

**Pull request merged**
