### PR TITLE
Add a dark theme for the website, overhaul usability and accessibility

### LINKED ISSUE #216: Add a dark theme for the official website
Like we already have for the [documentation](https://github.com/godotengine/godot-docs), we could look into adding a dark theme for the official website (based on the user's preference). This can be done relatively easily with `prefers-color-scheme` and CSS custom propeties – see [`custom.css`](https://github.com/godotengine/godot-docs/blob/master/_static/css/custom.css) for an example.

I could work on this if this feature is desired.

**Edit:** I started working on a prototype: https://github.com/Calinou/godot-website/tree/add-dark-theme

<details>

Screenshot of dark theme
</details>

### PR DESCRIPTION
**Pull request by Calinou**
Like for the documentation, this theme is used depending on the OS/browser's preference. On Firefox, the Dark Website Forcer add-on can be installed to use a dark theme if the OS isn't configured to use a dark theme.

This commit also improves hover/active feedback by using the CSS `filter` property. This behaves better with images and buttons without having to manually choose colors for every interaction.

This commit includes miscellaneous changes to the homepage design (such as the "A different way to make games" heading now being left-aligned instead of right-aligned).

A visible outline is now added to focused elements for better keyboard navigation.

Navigation bar links now have padding to be easier to click, both on desktop and on mobile.

Tested in Firefox 83 and Chromium 87.

This closes #216.

<details>
<summary>Screenshots</summary>

## Home

Screenshot_2020-12-22 Free and open source 2D and 3D game engine

## Features

Screenshot_2020-12-22 Features

## News

Screenshot_2020-12-22 News

## Community

Screenshot_2020-12-22 Community

## Download

Screenshot_2020-12-22 Download Linux

## License

Screenshot_2020-12-22 License
</details>

### CODE REVIEW

**Comment by YuriSizov** [comment]
Maybe it needs to be a bit less monochrome overall, so the blue bar at the top doesn't pop out so much.

**Comment by Calinou** [comment]
@pycbouh I've tried to use a gray color instead of dark blue, but then it ends up being a little too bland. Maybe a less saturated color (but still blue) would clash less with the dark gray below it.

**Comment by YuriSizov** [comment]
I was thinking more in terms of making grays hued a bit more towards blue/purple, colors we have in the light theme. Currently they are all in the middle, with a very small accent towards blue. In other words, I'd like if it had more color.

For example, YouTrack's dark theme is in the same general color range, but they use more bluish colors in accented areas (like inputs in the picture below):
image

**Review by akien-mga — APPROVED** [review]
Let's give it a spin and iterate from there.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
