### PR TITLE
Features: Remove Perforce and PlasticSCM as they're seldom tested

### PR DESCRIPTION
**Pull request by Calinou**
This partially addresses https://github.com/godotengine/godot-docs/issues/4584.

### CODE REVIEW

**Comment by akien-mga** [comment]
I think the referenced issue might be a misunderstanding. This statement here doesn't mean that Godot *supports* Perforce integration, but that its text-based and well compartmentalized scenes play nice with version control systems as a whole. The enumeration is just to match names that game developers might be familiar with (some might know they use Perforce at work without even knowing that it's a "version control system").

**Comment by akien-mga** [comment]
What should we do with this change? I'm OK merging it but as mentioned above, I don't think it's necessary (and many in the gamedev do use Plastic or Perforce so it's useful to let them understand that Godot will play nice with their favorite VCS - even without native integration).

**Comment by Calinou** [comment]
@akien-mga It seems Perforce itself is poorly supported due to read-only mode not playing well with Godot:

> There does not seem to be a perforce add-on, nor does it seem to natively work very well with perforce (read-only causes a lot of errors in the engine) The features page as well as the File system page mention Perforce by name as something that works well with Godot.
> —https://github.com/godotengine/godot-docs/issues/4584

Read-only mode (and file locking in general) are one of the big reasons game developers like to use Perforce instead of Git. Without proper read-only support in the Godot editor, I don't think we can claim to actually support Perforce.

**Comment by akien-mga** [comment]
Alright, makes sense.

**Pull request merged**
