### PR TITLE
Rework top and bottom navigation, reorganize the downloads page

### PR DESCRIPTION
**Pull request by YuriSizov**
As a follow-up to #397, this reworks was designed to both update some navigation presentation and find a place for the Teams page.

What this PR changes:

* Remove Patreon widget and replace it with the "Donate" link to the "Donate" page.
* Remove the "More" dropdown menu.
* Add the "About" link that directs to the "Contacts" page.
* Move the "Assets" link to the left and add the "Contribute" link to the right that links to the documentation for contributors.
* Improve the footer and add all the existing links there; this is the only place that links to the press kit now.
* Remove "Donate" and "Press Kit" as tabs of the "More/About" meta page and make them into dedicated pages.
* Add the "Teams" tab to the "About" meta page.
* Merge "Features" and "Showcase" into one meta page with old pages as tabs.
* Add the "Web Editor" tab to the "Download" page.
  * On the "Download" page, move the information about repository of past releases, GitHub releases and digital distribution platforms to the left side, and remove it from the other parts of the page.
  * Also remove the demos and step-by-step cards and put them under the right side section.

Many comparison screenshots!

Main page:
[Before](https://user-images.githubusercontent.com/11782833/178045163-9b67d8d8-0e81-4e4d-98da-59b6a3ac8986.jpg) | [After](https://user-images.githubusercontent.com/11782833/178045126-9d86e334-fc2a-420f-b058-7f31a2a6fb17.jpg)

Features page:
[Before](https://user-images.githubusercontent.com/11782833/178045301-98f08640-3f48-47c7-9590-1111fb75bddc.png) | [After](https://user-images.githubusercontent.com/11782833/178045309-05f0fcf3-016f-4404-915e-b0ee1da39f7f.png)

Footer:
[Before](https://user-images.githubusercontent.com/11782833/178045339-8d8192ca-b0f5-4392-a532-f46654ae4fc4.png) | [After](https://user-images.githubusercontent.com/11782833/178045346-e1a90507-5e78-400c-ad42-8dd125a3e138.png)

Downloads:
[Before](https://user-images.githubusercontent.com/11782833/178045372-46cf8325-0e26-426a-a5f0-1fdf8418eecd.png) | [After](https://user-images.githubusercontent.com/11782833/178045380-9d9fb10a-fd2e-4c56-9465-86046ea18af0.png)

Teams:
[Before](https://user-images.githubusercontent.com/11782833/178045437-a669fb01-9190-442e-8bd0-feb011348310.png) | [After](https://user-images.githubusercontent.com/11782833/178045452-43afdb2c-490f-4290-ae95-803415ab618c.png)

Donate:
[Before](https://user-images.githubusercontent.com/11782833/178045485-5fbe920d-e734-432d-a407-40551ed9a3da.png) | [After](https://user-images.githubusercontent.com/11782833/178045496-281fbe88-62c1-4fb3-8561-0337b18c42b8.png)

### CODE REVIEW

**Comment by Calinou** [comment]
Looks good to me!

The "current page" navigation bar highlight on the Donate page is still on About, is that intended?

Also, I'd probably make the Donate text more prominent like on https://github.com/godotengine/godot-website/pull/183. The Patreon banner has this nice eye-catching property; it would be a shame to lose that in the redesign.

**Comment by YuriSizov** [comment]
> The "current page" navigation bar highlight on the Donate page is still on About, is that intended?

Nope, my mistake, fixed!

And added the color as suggested. Here's a very lovely "Donate" button in light theme:

[On the features page](https://user-images.githubusercontent.com/11782833/178049359-1d2e519e-7998-4ee6-9690-6961717309fb.png)
[And active, on the donate page](https://user-images.githubusercontent.com/11782833/178049424-32f72f28-f3d5-4fda-8eae-9b25317be5e9.png)

**Comment by coppolaemilio** [comment]
# Elements too close to the sides

The nav bar borders are touching the edge of the screen if the screen is small.
Screen Shot 2022-07-12 at 02 17 18

Same happens on the footer @ 1201px 

image


Haven't gone too deep but it might be current setup of the `.container` class that has a fixed width of 1200px. 
Adding something like `padding: 0 20px; box-sizing: border-box;` should fix the issue, but other pages might get impacted so a whole scrub of the site site would be recommended.

# Unification of the Showcase and the Features
Not really a fan of the location for the showcase/features tab. It can easily be missed, but not a big deal if a redesign of the entire page is coming eventually. In the About page it is more obvious because the tabs are connecting the tab color with the content, but the first section of the Features page is not, so it feels disjointed:

Screen Shot 2022-07-12 at 02 27 26

Screen Shot 2022-07-12 at 02 28 35

# Footer 
The footer is not centered on mobile:
Screen Shot 2022-07-12 at 02 32 20

**Comment by YuriSizov** [comment]
> Elements too close to the sides

That's a pre-existing issue, but yeah, with the donate button in the header it is way more annoying. Fixed!

> The footer is not centered on mobile

Oops, fixed.

> Not really a fan of the location for the showcase/features tab. It can easily be missed, but not a big deal if a redesign of the entire page is coming eventually. In the About page it is more obvious because the tabs are connecting the tab color with the content, but the first section of the Features page is not, so it feels disjointed

Yeah, I get what you mean. Would this be a stupid solution? :D Edit: Pushed it like that, but can revert it if you think it's worse now.

image

**Comment by coppolaemilio** [comment]
I think it looks good if we remove the "dark" class from that element. That way it is much easier to spot the tab. I still think that a better location for the showcase could be found but we can revisit that in a future PR. 

Screen Shot 2022-07-12 at 21 20 31

Screen Shot 2022-07-12 at 21 20 20

**Comment by YuriSizov** [comment]
Fair enough. I think we should tackle this page soon anyway. The pictures, and probably some of the taglines need updating, very much so. The animation one shows Godot 2.1 UI 👀

**Comment by Calinou** [comment]
Could you change the `main.css` version identifier from `?7` to `?8` [here](https://github.com/YuriSizov/godot-website/blob/015b4222590dd240b3b48a99d2898d02f8d7118e/themes/godotengine/partials/head.htm#L40)?

Once this is done, this can be merged :slightly_smiling_face:

**Comment by coppolaemilio** [comment]
haha that's some advanced cache invalidation! We can probably get a number from the commit to use there or some other reference to the file last modification

**Comment by Calinou** [comment]
> haha that's some advanced cache invalidation! We can probably get a number from the commit to use there or some other reference to the file last modification

I didn't want to use an approach that requires reading the file every time (or having to run an external program), so using an incremental key works well enough here.

**Comment by YuriSizov** [comment]
> Could you change the `main.css` version identifier from `?7` to `?8` [here](https://github.com/YuriSizov/godot-website/blob/015b4222590dd240b3b48a99d2898d02f8d7118e/themes/godotengine/partials/head.htm#L40)?
> 
> Once this is done, this can be merged 🙂

Done! 👍

**Review by Calinou — APPROVED** [review]
Thanks a ton!

**Pull request merged**
