### PR TITLE
Link to Linux desktop integration instructions (#802)

### PR DESCRIPTION
**Pull request by computer-science-student**
Add a guide to install Godot on Linux, Windows, and macOS.

### CODE REVIEW

**Comment by coppolaemilio** [comment]
Is this change necessary? Is it responding to any issue in particular?

**Comment by computer-science-student** [comment]
Yes, this pull request is responding to this issue: https://github.com/godotengine/godot-website/issues/802 

Let me know if you have any questions, suggestions, or concerns.

**Review by Calinou — COMMENTED** [review]
I built the website locally but don't see the new block on the Download page:

image

**Edit:** This is because the line is only present on the post-download popup.

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. The links go to the corresponding FAQ section correctly.

image

**Comment by coppolaemilio** [comment]
Thanks!

**Pull request merged**
