### PR TITLE
Update designs for text-heavy pages

### PR DESCRIPTION
**Pull request by bits-by-brandon**
Tightens up the layout and styles of the text heavy about/* pages

## Makes the following changes:
- creates new `.container-text` style to constrain text to a readable max-width
- creates subtle borders around table rows
- removes colons on table headers
- creates better header spacing for long text
 
Screen Shot 2022-07-22 at 11 09 08 AM

Screen Shot 2022-07-22 at 11 09 21 AM

Screen Shot 2022-07-22 at 11 09 00 AM

### CODE REVIEW

**Comment by bits-by-brandon** [comment]
@Calinou Any revisions needed, or can this get merged?

**Review by Calinou — APPROVED** [review]
Thanks a ton!

**Comment by Calinou** [comment]
I noticed that the text is offset to the right on mobile. Can you look into this?

image

**Comment by bits-by-brandon** [comment]
Yeah I'll take a look later today

**Pull request merged**
