### PR TITLE
Add a missing full stop in education.html

### PR DESCRIPTION
**Pull request by User670**

### CODE REVIEW

**Comment by YuriSizov** [comment]
Thanks for opening a PR! I think formatting of the entire section can be improved. The text of the FAQ was probably copied from elsewhere and is very awkwardly formatted with arbitrary line breaks. Long lines need to be split, but it needs to be done consistently, and not with single words. If you are interested in making these improvements, this would greatly enhance your PR.

**Comment by User670** [comment]
> Thanks for opening a PR! I think formatting of the entire section can be improved. The text of the FAQ was probably copied from elsewhere and is very awkwardly formatted with arbitrary line breaks. Long lines need to be split, but it needs to be done consistently, and not with single words. If you are interested in making these improvements, this would greatly enhance your PR.

@YuriSizov I'm not familiar with HTML style guides. Are there any style guides this project should follow? Or should I just format as I see fit?

**Comment by YuriSizov** [comment]
In this case this is mostly about text formatting rather than some HTML style guidelines. To give you an example, for the paragraph that you have edited:

```
		<p>You can use the Godot Engine on the browser without the need to install it on your device.<br>This is useful if
			you
			are restricted by your organization or limited by the device being used and you can't install software locally.</p>
```

this can be done:

```
		<p>
			You can use the Godot Engine on the browser without the need to install it on your device.
			<br>
			This is useful if you are restricted by your organization or limited by the device being used
			and you can't install software locally.
		</p>
```

**Comment by JohnVeness** [comment]
I think the rendered text would look better without the `<br>`s, too.

**Comment by babakfp** [comment]
Hey there! I noticed the feedback about text formatting, and it seems like the paragraph could use some touch-ups for better readability. However, I'd like to remind everyone that the main purpose of this pull request was just to add a period.

So, how about suggesting a separate pull request for the formatting tweaks? That way, we can keep this one straightforward and in line with its original purpose. Plus, it's worth considering using a tool like Prettier for automated formatting to keep things consistent.

**Comment by YuriSizov** [comment]
@babakfp We prefer when PRs are more substantial than that. Here we have a great opportunity to make a meaningful and useful change, which is why we advise the contributor to do so.

I'm not sure where you're coming from with your reply, but I would like to remind **you** that I'm offering this feedback as a project maintainer and not just to randomly bother someone.

**Comment by babakfp** [comment]
I understand your role as a project maintainer and your desire for substantial changes. However, it's important to remember the context of this pull request. The initial purpose was a simple punctuation correction, and the contributor doesn't know HTML or code formatting.

While I appreciate your input, it's worth noting that code formatting and other non-related changes should ideally be handled separately and not manually. This keeps things efficient and avoids complicating simple PRs.

If you feel strongly about making additional changes, it may be more appropriate to create a new issue or pull request specifically addressing those concerns. This way, we can ensure that contributions align with the project's goals and maintain clarity in the development process. Thank you for your understanding.

**Comment by YuriSizov** [comment]
@babakfp I appreciate your desire to be helpful, but you are currently being disruptive and derailing PR discussion. I would advise you to stop with this line of comments. I'm going to hide them as offtopic and expect you to drop the matter.

**Comment by coppolaemilio** [comment]
Closing this one. The page needs a full remake. Thanks!

**Pull request closed without merging**
