### PR TITLE
Add BLASTRONAUT and Usagi Shima to showcase

### PR DESCRIPTION
**Pull request by coppolaemilio**
Another game added to the showcase. This game also is showcased on the hero of the website.

### CODE REVIEW

**Comment by coppolaemilio** [comment]
@YuriSizov okay, sorry for assigning twice, just wanted to squeeze in another game in this PR. 
Should be ready to merge 👍

**Comment by YuriSizov** [comment]
I don't think assigning twice requires me to do twice as much work :P

**Comment by YuriSizov** [comment]
Maybe it's a bigger question than needed for this PR, but should we have a capsule image with an update title that's going to get outdated by the next update?

**Comment by coppolaemilio** [comment]
Good point... I don't have the generic capsule yet unfortunately. I'm fine updating it when I do get it, but if you prefer to wait until then there isn't too much of a rush with merging this one

**Comment by YuriSizov** [comment]
@coppolaemilio If there is no rush, I'd wait until tomorrow. Gives us time to wait from the creator, and gives me time to chill this evening :)

**Comment by coppolaemilio** [comment]
Sounds like a plan :)

**Comment by coppolaemilio** [comment]
Got a new capsule in place for BLASTRONAUT :)

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Pull request merged**
