### PR TITLE
Added FAQ to the Navbar

### PR DESCRIPTION
**Pull request by silverag2002**
godotengine/godot-question2answer#9 I have added a link to the FAQ in the Navbar

### CODE REVIEW

**Comment by YuriSizov** [comment]
That issue is for the Q&A website, not for the main website. Sorry for the confusion.

**Comment by silverag2002** [comment]
Screenshot 2022-07-22 at 18 37 38
@YuriSizov Is this the Q&A website of Godot Engine
If yes, how do I contribute to it as it is Powered by Question2Answer

**Comment by YuriSizov** [comment]
Yes, that's the one. I think @Calinou needs to edit it directly, there is no public repo.

**Comment by Calinou** [comment]
I added a link to the FAQ in the sidebar: 

image

**Pull request closed without merging**
